### ISSUE TITLE
Nested include support

### ISSUE THREAD

**Issue by ThibautPlg** [sunlei/zsh-ssh#15]
Hello,
First of all, thanks for this plugin.

I've noticed that nested includes aren't supported yet. This is almost a duplicate of this issue: https://github.com/sunlei/zsh-ssh/issues/9 .
To reuse toddeye's example, here is what my config looks like:
```
[~/.ssh/config file]
include config.d/*

[~/.ssh/config.d file listing]
include1
include2

[~/.ssh/config.d/include1]
include ~/.ssh/config.d/another-directory/*
```

Isn't a major issue, as copying the include line into an other config file is an easy workaround.

Best regards,

**Comment by sunlei** [comment]
see https://github.com/sunlei/zsh-ssh/commit/1420736b9d9629ccc67b4ce39a24501668
