### ISSUE TITLE
still working in 2022?

### ISSUE THREAD

**Issue by lokize** [sunlei/zsh-ssh#4]
i using autocomplete plugin and when i try press space after ssh command i have this error: 

`fzf-complete-ssh:24: command not found: fzf`

**Comment by bdoublet91** [comment]
Yeah it's working
Make sure you have [fzf](https://github.com/junegunn/fzf) installed.
sudo apt install fzf
if you are on linux

**Comment by lokize** [comment]
working good now thank you very much!
