### ISSUE TITLE
ssh config.d and include support

### ISSUE THREAD

**Issue by toddeye** [sunlei/zsh-ssh#9]
Is it possible to have the plugin evaluate ssh host definitions defined in the config.d subdirectory.

```
[~/.ssh/config file]
include config.d/*

[~/.ssh/config.d file listing]
include1
include2
...
```

**Comment by sunlei** [comment]
see https://github.com/sunlei/zsh-ssh/commit/d3b8ce35a0ad3cbfaecb31d9535af270c6ff0fc2
